### ISSUE TITLE
Universities/Schools/Institute support list sofar

### ISSUE THREAD

**Issue by ZibanPirate** [dzcode-io/kuliya#23]
This issue is for tracking support for universities/schools/institutes that we plan to add in kuliya

**Universities/Schools/Institutes**

1. [x] UMKB #16 (Add University of Mohamed Khider Biskra)
2. [ ] UMMTO #22 (Add University Of Mouloud Mammri Tizi-Ouzou)
3. [ ] USTHB #21 (Add University Of Science And Technology Houari Boumediene Algiers)
4. [ ] [code?] #19 (Oran University1 Ahmed Ben Bella)
5. [ ] IGEE #18 (Institut de Génie Electrique et Electronique IGEE ex-enelec Boumerdes)
6. [ ] UMBB #17 (Université M'hamed Bougara Boumerdes)

If you you don't find yours listed here, and you want to add it to the dataset, please comment below or [create an issue](https://github.com/dzcode-io/kuliya/issues/new/choose) with the missing univ/school/institute and who should work on it

If you would like to work on any of the tasks listed, please comment below with the task number: #task-number
